name: webtu_v2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  cached_memory_image: ^1.5.0
  font_awesome_flutter: ^10.7.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  flutter_credit_card_ui: ^0.0.4
  qr_flutter: ^4.1.0
  adaptive_theme: ^3.6.0
  google_fonts: ^6.2.1

  #network
  http: ^1.3.0

  #state
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^14.8.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png
    - assets/card/card_student_empty_front.webp
    - assets/card/card_student_back.webp
    - assets/card/onou.webp
